// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: admin.sql

package db

import (
	"context"
)

const seedAdmin = `-- name: SeedAdmin :one
INSERT INTO admins (full_name,email,password, role)
VALUES('Brian Kibet','briankibet@gmail.com','1234','Registration') RETURNING full_name
`

func (q *Queries) SeedAdmin(ctx context.Context) (string, error) {
	row := q.queryRow(ctx, q.seedAdminStmt, seedAdmin)
	var full_name string
	err := row.Scan(&full_name)
	return full_name, err
}
