// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: contestants.sql

package db

import (
	"context"
)

const registerCandidate = `-- name: RegisterCandidate :one
INSERT INTO contestants(full_name,password,position, description)
VALUES ($1,$2,$3,$4) RETURNING id, full_name, email, password, position, registered_at, description
`

type RegisterCandidateParams struct {
	FullName    string `json:"fullName"`
	Password    string `json:"password"`
	Position    string `json:"position"`
	Description string `json:"description"`
}

func (q *Queries) RegisterCandidate(ctx context.Context, arg RegisterCandidateParams) (Contestant, error) {
	row := q.queryRow(ctx, q.registerCandidateStmt, registerCandidate,
		arg.FullName,
		arg.Password,
		arg.Position,
		arg.Description,
	)
	var i Contestant
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.Position,
		&i.RegisteredAt,
		&i.Description,
	)
	return i, err
}
