// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: voter.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const registerVoter = `-- name: RegisterVoter :one
INSERT INTO voters(full_name, email, registered_at,voters_public_address)
VALUES($1,$2,$3,$4) RETURNING id
`

type RegisterVoterParams struct {
	FullName            string    `json:"fullName"`
	Email               string    `json:"email"`
	RegisteredAt        time.Time `json:"registeredAt"`
	VotersPublicAddress string    `json:"votersPublicAddress"`
}

func (q *Queries) RegisterVoter(ctx context.Context, arg RegisterVoterParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.registerVoterStmt, registerVoter,
		arg.FullName,
		arg.Email,
		arg.RegisteredAt,
		arg.VotersPublicAddress,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const totalVotedVoters = `-- name: TotalVotedVoters :one
SELECT COUNT(email) FROM voters WHERE voted = true
`

func (q *Queries) TotalVotedVoters(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.totalVotedVotersStmt, totalVotedVoters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const totalVotersNum = `-- name: TotalVotersNum :one
SELECT COUNT(email) FROM voters
`

func (q *Queries) TotalVotersNum(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.totalVotersNumStmt, totalVotersNum)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateVoter = `-- name: UpdateVoter :one
UPDATE voters SET email = $1 WHERE email=$2 RETURNING id, full_name, email, registered_at, voted_at, voted, voters_public_address
`

type UpdateVoterParams struct {
	Email   string `json:"email"`
	Email_2 string `json:"email2"`
}

func (q *Queries) UpdateVoter(ctx context.Context, arg UpdateVoterParams) (Voter, error) {
	row := q.queryRow(ctx, q.updateVoterStmt, updateVoter, arg.Email, arg.Email_2)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.RegisteredAt,
		&i.VotedAt,
		&i.Voted,
		&i.VotersPublicAddress,
	)
	return i, err
}
