name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:14.4
        env:
           POSTGRES_USER: brian
           POSTGRES_PASSWORD: brian
           POSTRES_DB: election
        ports:
          - 5432:5432

    steps:
      - name: Set Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install golang migrateUp
        run:  |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-386.tar.gz | tar xvz
          sudo  mv migrate /usr/bin

      - name: Database migrations
        run: make migrateUp

      - name: run Test
        run: |
          make test